baseURL = "https://localhost:1313"
languageCode = "en-us"
title = "St John's Community Garden"
theme = "stjohn"
relativeURLS = true
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
copyright = "Copyright 2021-{year} St John's Garden Community. All rights reserved."

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]


[module]
    [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"


[params]
  pre = "<h3>Active"
  post = "</h3>"
  

  [menu]
    [[menu.main]]
    identifier = "campaigns"
    name = "Campaigns"
    url = "/campaigns/"
    weight = 20
 
