baseURL = "https://stcg.ntlify.app"
languageCode = "en-us"
title = "St John's Community Garden"
theme = "stjohn"
relativeURLS = true
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
copyright = "Community Garden - St John's Walton {year}."

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]


[module]
    [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"


[params]
  pre = "<h3>Active"
  post = "</h3>"
  
  [menu]
    [[menu.main]]
    identifier = "works"
    name = "Works"
    url = "/works/"
    weight = 20
    
    [[menu.main]]
    identifier = "design"
    name = "Design"
    url = "/design/"
    weight = 60

    [[menu.main]]
    identifier = "plants"
    name = "Plants"
    url = "/plants/"
    weight = 40

    [[menu.main]]
    identifier = "wildlife"
    name = "Wildlife"
    url = "/wildlife"
    weight = 50

    [[menu.main]]
    identifier = "precedents"
    name = "Precedents"
    url = "/precedents"
    weight = 60

